What You Will Learn:
Core NumPy operations including array creation, manipulation, and basic array operations.
Skills in handling one-dimensional and multi-dimensional arrays.


What You Will Create:
A series of NumPy arrays demonstrating different operations, ranging from simple array creation to more complex manipulations.


🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output:



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
# Import the NumPy library to enable fast array creation and manipulation
import numpy as np
# Generate a 1D array with values from 0 up to (but excluding) 10
array_1d = np.arange(10)

# Display the generated array to verify the output matches the requirements
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:



array([3, 2, 0, 1, 2])

In [2]:
# Define a Python list containing floating-point numbers and integers
original_list = [3.14, 2.17, 0, 1, 2]

# Convert the Python list into a standard NumPy array
float_array = np.array(original_list)

# Display the initial array to check its values and auto-detected data type
print("Original Float Array:")
print(float_array)

Original Float Array:
[3.14 2.17 0.   1.   2.  ]


In [3]:
# Convert the array data type to integer using the .astype() method
integer_array = float_array.astype(int)

# Display the final converted array to verify the result
print("\nConverted Integer Array:")
print(integer_array)


Converted Integer Array:
[3 2 0 1 2]


🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


In [4]:
# Import the NumPy library to handle array generation and reshaping
import numpy as np

# Create a 1D array with values from 1 up to 10 (10 is excluded, so it stops at 9)
flat_array = np.arange(1, 10)

# Display the flat array to understand its starting state
print("Flat 1D Array:")
print(flat_array)

Flat 1D Array:
[1 2 3 4 5 6 7 8 9]


In [5]:
# Reshape the 1D array into a 2D multi-dimensional array with 3 rows and 3 columns
matrix_3x3 = flat_array.reshape(3, 3)

# Display the final 3x3 array to verify the structured output
print("\nMulti-Dimensional 3x3 Array:")
print(matrix_3x3)


Multi-Dimensional 3x3 Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:



array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])

In [6]:
# Set a random seed so the generated numbers remain the same every run
np.random.seed(42)

# Create a 2D array of shape (4 rows, 5 columns) filled with random floats between 0 and 1
random_matrix = np.random.rand(4, 5)

# Display the generated matrix to see the raw random values
print("Original Random Matrix:")
print(random_matrix)

Original Random Matrix:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]


🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:



array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


In [7]:
# Create the given 2D NumPy array with 3 rows and 5 columns
array = np.array([
    [21, 22, 23, 22, 22],  # Row 0 (First row)
    [20, 21, 22, 23, 24],  # Row 1 (Second row)
    [21, 22, 23, 22, 22]   # Row 2 (Third row)
])

# Display the full array to visualize its rows
print("Original 2D Array:")
print(array)

Original 2D Array:
[[21 22 23 22 22]
 [20 21 22 23 24]
 [21 22 23 22 22]]


In [8]:
# Select the second row using index 1 (remember, counting starts at 0)
second_row = array[1]

# Display the extracted row to verify the output matches the requirement
print("\nExtracted Second Row:")
print(second_row)


Extracted Second Row:
[20 21 22 23 24]


🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:



array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
# Create an initial 1D NumPy array with numbers from 0 to 9
original_array = np.arange(10)

# Display the initial array to see the starting order
print("Original Array:")
print(original_array)

Original Array:
[0 1 2 3 4 5 6 7 8 9]


In [10]:
# Reverse the array elements by using a slice with a step of -1
reversed_array = original_array[::-1]

# Display the reversed array to verify the result
print("\nReversed Array:")
print(reversed_array)


Reversed Array:
[9 8 7 6 5 4 3 2 1 0]


🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# Create a 4x4 identity matrix
# The function np.eye() automatically places 1s on the diagonal and 0s elsewhere
identity_matrix = np.eye(4)

# Display the generated matrix to verify the output matches the requirements
print("Generated 4x4 Identity Matrix:")
print(identity_matrix)

Generated 4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:



Sum: 45, Average: 4.5

In [12]:
# Create a 1D NumPy array with values from 0 to 9
array_1d = np.arange(10)

# Display the array to see the numbers we are aggregating
print("Original 1D Array:")
print(array_1d)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]


In [13]:
# Calculate the total sum of all elements in the array
total_sum = np.sum(array_1d)

# Calculate the average (mean) value of the elements
average_value = np.mean(array_1d)

# Display the final results to match the expected output format
print(f"\nSum: {total_sum}, Average: {average_value}")


Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [14]:
# Create a 1D array with values from 1 up to 21 (21 is excluded, so it stops at 20)
flat_array = np.arange(1, 21)

# Display the flat array to see the sequential numbers
print("Original 1D Array:")
print(flat_array)

Original 1D Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [15]:
# Reshape the 1D array into a 2D matrix with 4 rows and 5 columns
matrix_4x5 = flat_array.reshape(4, 5)

# Display the reshaped multi-dimensional array
print("\nReshaped 4x5 Matrix:")
print(matrix_4x5)


Reshaped 4x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:



array([1, 3, 5, 7, 9])

In [16]:
# Create a 1D NumPy array with values from 0 to 9
array_1d = np.arange(10)

# Create a boolean mask: True for odd numbers, False for even numbers
odd_mask = (array_1d % 2 != 0)

# Display the mask to see how NumPy tags each position
print("Boolean Mask (Is number odd?):")
print(odd_mask)

Boolean Mask (Is number odd?):
[False  True False  True False  True False  True False  True]


In [17]:
# Extract elements where the mask condition is True
odd_numbers = array_1d[odd_mask]

# Display the filtered array
print("\nExtracted Odd Numbers:")
print(odd_numbers)


Extracted Odd Numbers:
[1 3 5 7 9]
